### ISSUE TITLE
Amend neuronym from `kb8` to `k8s`

### ISSUE THREAD

**Issue by ajlanghorn** [UKHomeOffice/email-api#8]
In https://github.com/UKHomeOffice/email-api/pull/1, examples for use of this project with Kubernetes are provided. On the master branch, Kubernetes is referred to a few times as `kb8`, instead of `k8s`, as is the generally accepted neuronym. I spun out a quick branch at https://github.com/UKHomeOffice/email-api/compare/master...ajlanghorn:kb8-k8s as starters for ten, but it might need some additional work as I didn't unpack any binaries etc. to check for `kb8` references inside those.

If the outcome of this issue is :+1:'d, I'll PR that branch to this repo.

**Comment by PurpleBooth** [comment]
I've used kb8's loads of places (on other repositories), but now I look at the official repository, you're right, k8s is the correct abbreviation.

![image](https://cloud.githubusercontent.com/assets/133327/10587808/da4ec4ba-769a-11e5-8b53-86c4e4a8a005.png)

 Your branch looks spot on, if you create a PR for it, I'll merge it in :+1: 

_goes off to find all the other repositories she's used kb8s rather than k8s_

**Comment by ajlanghorn** [comment]
Thanks @PurpleBooth!

**Comment by ajlanghorn** [comment]
Fixed by #9.
